# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import esto_rpc_pb2 as esto__rpc__pb2


class EstoStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreRecord = channel.unary_unary(
                '/esto_rpc.Esto/StoreRecord',
                request_serializer=esto__rpc__pb2.StoreRequest.SerializeToString,
                response_deserializer=esto__rpc__pb2.StoreReply.FromString,
                )
        self.ReadRecord = channel.unary_unary(
                '/esto_rpc.Esto/ReadRecord',
                request_serializer=esto__rpc__pb2.ReadRequest.SerializeToString,
                response_deserializer=esto__rpc__pb2.ReadEventList.FromString,
                )


class EstoServicer(object):
    """Missing associated documentation comment in .proto file"""

    def StoreRecord(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRecord(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreRecord,
                    request_deserializer=esto__rpc__pb2.StoreRequest.FromString,
                    response_serializer=esto__rpc__pb2.StoreReply.SerializeToString,
            ),
            'ReadRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRecord,
                    request_deserializer=esto__rpc__pb2.ReadRequest.FromString,
                    response_serializer=esto__rpc__pb2.ReadEventList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'esto_rpc.Esto', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Esto(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def StoreRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/esto_rpc.Esto/StoreRecord',
            esto__rpc__pb2.StoreRequest.SerializeToString,
            esto__rpc__pb2.StoreReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/esto_rpc.Esto/ReadRecord',
            esto__rpc__pb2.ReadRequest.SerializeToString,
            esto__rpc__pb2.ReadEventList.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
