# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esto_rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='esto_rpc.proto',
  package='esto_rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x65sto_rpc.proto\x12\x08\x65sto_rpc\"^\n\x0cStoreRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x12\n\nevent_data\x18\x04 \x01(\t\"\x1d\n\nStoreReply\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0bReadRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\"0\n\rReadEventList\x12\x1f\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x0f.esto_rpc.Event\"j\n\x05\x45vent\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x02 \x01(\t\x12\x12\n\nevent_name\x18\x03 \x01(\t\x12\x12\n\nevent_data\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x32\x81\x01\n\x04\x45sto\x12;\n\x0bStoreRecord\x12\x16.esto_rpc.StoreRequest\x1a\x14.esto_rpc.StoreReply\x12<\n\nReadRecord\x12\x15.esto_rpc.ReadRequest\x1a\x17.esto_rpc.ReadEventListb\x06proto3'
)




_STOREREQUEST = _descriptor.Descriptor(
  name='StoreRequest',
  full_name='esto_rpc.StoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='esto_rpc.StoreRequest.entity_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='esto_rpc.StoreRequest.entity_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_name', full_name='esto_rpc.StoreRequest.event_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='esto_rpc.StoreRequest.event_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=122,
)


_STOREREPLY = _descriptor.Descriptor(
  name='StoreReply',
  full_name='esto_rpc.StoreReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='esto_rpc.StoreReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=153,
)


_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='esto_rpc.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='esto_rpc.ReadRequest.entity_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=187,
)


_READEVENTLIST = _descriptor.Descriptor(
  name='ReadEventList',
  full_name='esto_rpc.ReadEventList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='esto_rpc.ReadEventList.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=237,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='esto_rpc.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='esto_rpc.Event.entity_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='esto_rpc.Event.entity_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_name', full_name='esto_rpc.Event.event_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_data', full_name='esto_rpc.Event.event_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='esto_rpc.Event.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=345,
)

_READEVENTLIST.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['StoreRequest'] = _STOREREQUEST
DESCRIPTOR.message_types_by_name['StoreReply'] = _STOREREPLY
DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['ReadEventList'] = _READEVENTLIST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreRequest = _reflection.GeneratedProtocolMessageType('StoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREREQUEST,
  '__module__' : 'esto_rpc_pb2'
  # @@protoc_insertion_point(class_scope:esto_rpc.StoreRequest)
  })
_sym_db.RegisterMessage(StoreRequest)

StoreReply = _reflection.GeneratedProtocolMessageType('StoreReply', (_message.Message,), {
  'DESCRIPTOR' : _STOREREPLY,
  '__module__' : 'esto_rpc_pb2'
  # @@protoc_insertion_point(class_scope:esto_rpc.StoreReply)
  })
_sym_db.RegisterMessage(StoreReply)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'esto_rpc_pb2'
  # @@protoc_insertion_point(class_scope:esto_rpc.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadEventList = _reflection.GeneratedProtocolMessageType('ReadEventList', (_message.Message,), {
  'DESCRIPTOR' : _READEVENTLIST,
  '__module__' : 'esto_rpc_pb2'
  # @@protoc_insertion_point(class_scope:esto_rpc.ReadEventList)
  })
_sym_db.RegisterMessage(ReadEventList)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'esto_rpc_pb2'
  # @@protoc_insertion_point(class_scope:esto_rpc.Event)
  })
_sym_db.RegisterMessage(Event)



_ESTO = _descriptor.ServiceDescriptor(
  name='Esto',
  full_name='esto_rpc.Esto',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=348,
  serialized_end=477,
  methods=[
  _descriptor.MethodDescriptor(
    name='StoreRecord',
    full_name='esto_rpc.Esto.StoreRecord',
    index=0,
    containing_service=None,
    input_type=_STOREREQUEST,
    output_type=_STOREREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadRecord',
    full_name='esto_rpc.Esto.ReadRecord',
    index=1,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_READEVENTLIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTO)

DESCRIPTOR.services_by_name['Esto'] = _ESTO

# @@protoc_insertion_point(module_scope)
